### ISSUE TITLE
Pool not working on checking hashrate.

### ISSUE THREAD

**Issue by MasterDeflate** [webchain-network/webchain-pool#9]
Here is a full installation of the pool and there still problem with stats, i followed daniel-web tutorial and told him about this. The problem is that a miner connect to pool and share alot shares but when you check stats for that address its empty (blank page white), while if he get a block (then it work). Also at ./build.sh it show some warning messages. I will show full procedure, and no one still wanna help me fix this.

Check via pastebin --> https://pastebin.com/ipqP0BUa

This is tested on:
```
root@server2:/etc/systemd/system# cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
root@server2:/etc/systemd/system# uname -a
Linux server2.webchain.live 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@server2:/etc/systemd/system#
```

While i do the tests and on Ubuntu 18.04 , but same problem i get and then i move to Ubuntu 16.04 as recommended (x64 was both versions i test).

**Comment by yasser-pro** [comment]
my pool don't work, please chack http://51.140.45.8/#/ 
also webchaind.service failed start .. what I can do to run my pool ???

`ro@freevps1:/home/webchain/webchain-pool/www/config$ sudo systemctl status webchaind.service
● webchaind.service - Webchaind
   Loaded: loaded (/etc/systemd/system/webchaind.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Sun 2019-04-07 03:24:48 UTC; 42min ago
  Process: 3114 ExecStart=/home/webchain/webchaind --rpc --rpcaddr 127.0.0.1 --unlock “0x618c2a363e41dde709ff2
 Main PID: 3114 (code=exited, status=1/FAILURE)

Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Unit entered failed state.
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Failed with result 'exit-code'.
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Service hold-off time over, scheduling restart.
Apr 07 03:24:48 freevps1 systemd[1]: Stopped Webchaind.
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Start request repeated too quickly.
Apr 07 03:24:48 freevps1 systemd[1]: Failed to start Webchaind.
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Unit entered failed state.
Apr 07 03:24:48 freevps1 systemd[1]: webchaind.service: Failed with result 'start-limit-hit'.
`
